# Generated by Django 4.2.2 on 2023-07-12 17:29
# Modified to fix automatically generated errors:
# - Martim Pinheiro Alves, n46286
# - Pedro Jorge, n47498
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionModel',
            fields=[
                ('id_i', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrashCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_c', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('qr_code_str', models.CharField(max_length=20, unique=True)),
                ('qr_code_img', models.BinaryField(null=True, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institutionmodel')),
            ],
            options={
                'unique_together': {('institution', 'name')},
                'unique_together': {('institution', 'id_c')},
            },
        ),
        migrations.CreateModel(
            name='DrawerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_d', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('n_lins', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('n_cols', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('qr_code_str', models.CharField(max_length=20, unique=True)),
                ('qr_code_img', models.BinaryField(null=True, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institutionmodel')),
                ('crashcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crashcartmodel')),
            ],
            options={
                'unique_together': {('institution', 'crashcart', 'name')},
                'unique_together': {('institution', 'crashcart', 'id_d')},
            },
        ),
        migrations.CreateModel(
            name='SlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_s', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('s_adj_hor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('s_adj_ver', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name_prod', models.CharField(max_length=50)),
                ('vol_weight', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=100, null=True)),
                ('max_quant', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valid_date', models.DateField(null=True)),
                ('qr_code_str', models.CharField(max_length=20)),
                ('qr_code_img', models.BinaryField(null=True, unique=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institutionmodel')),
                ('crashcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crashcartmodel')),
                ('drawer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drawermodel')),
            ],
            options={
                'unique_together': {('institution', 'crashcart', 'drawer', 'name')},
                'unique_together': {('institution', 'crashcart', 'drawer', 'id_s')},
            },
        ),
    ]

